### ISSUE TITLE
🐛 Bug Report: Integration with Nuxt 500 error - self hosted version

### ISSUE THREAD

**Issue by AzotoN1** [notifirehq/notifire#5684]
### 📜 Description

When go step by step with documentation and include all data to component I get an error:

`[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'querySelectorAll')
  at uw (F:\Projekty\FindInvestor\@novu\notification-center-vue:6956:22)
  at TF (F:\Projekty\FindInvestor\@novu\notification-center-vue:7965:11)
  at F:\Projekty\FindInvestor\@novu\notification-center-vue:8038:9
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.runModule (/F:/Projekty/FindInvestor/node_modules/vite-node/dist/client.mjs:356:5)
  at async ViteNodeRunner.directRequest (/F:/Projekty/FindInvestor/node_modules/vite-node/dist/client.mjs:340:5)
  at async ViteNodeRunner.cachedRequest (/F:/Projekty/FindInvestor/node_modules/vite-node/dist/client.mjs:189:14)
  at async ViteNodeRunner.dependencyRequest (/F:/Projekty/FindInvestor/node_modules/vite-node/dist/client.mjs:233:12)
  at async F:\Projekty\FindInvestor\plugins\novu.ts:2:31
  at async ViteNodeRunner.runModule (/F:/Projekty/FindInvestor/node_modules/vite-node/dist/client.mjs:356:5)`

### 👟 Reproduction steps

1. Install dependency
2. Make plugin
3. Make component with all data from documentation
4. Run project

### 👍 Expected behavior

Working without errors

### 👎 Actual Behavior with Screenshots

![code](https://github.com/novuhq/novu/assets/28571858/a45b7b7a-935d-49cd-8c40-a1e2878a52b5)
![code](https://github.com/novuhq/novu/assets/28571858/36d3b38c-2b20-4d22-8242-8f3d034cc2b0)
![code](https://github.com/novuhq/novu/assets/28571858/7903e9a9-8897-414a-9fad-d8061bd77091)

### Novu version

0.24.1

### npm version

yarn 1.22.21

### node version

20.2.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by michaldziuba03** [comment]
Hello @AzotoN1 

I don't use Vue or Nuxt but I was able to make it work, check out my example: https://stackblitz.com/edit/nuxt-starter-xqpfkd

Keep in mind that Novu notification center is client only component and if `querySelectorAll` is undefined I would suspect that Nuxt tries to do something in server context.
