### ISSUE TITLE
🐛 Bug Report: QuickStart Steps for Express Js produce Error

### ISSUE THREAD

**Issue by legend1998** [notifirehq/notifire#6084]
### 📜 Description

Follow QuickStart Steps For Express Server

start the express server and BOOM

### 👟 Reproduction steps

follow quickStart Express steps

start express and BOOM

### 👍 Expected behavior

it should start the express on 4000 port easily

### 👎 Actual Behavior with Screenshots

TypeError: e is not iterable
    at ne.addWorkflows (D:\practical\expressServer\node_modules\@novu\framework\dist\express.js:21:12052)
    at new ae (D:\practical\expressServer\node_modules\@novu\framework\dist\express.js:25:2598)
    at kr (D:\practical\expressServer\node_modules\@novu\framework\dist\express.js:25:6079)
    at file:///D:/practical/expressServer/app.js:11:22
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.1

### Novu version

2.0.0-canary.7

### npm version

9.7.1

### node version

 20.11.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by legend1998** [comment]
Found The Problem Closing it
