### ISSUE TITLE
🐛 Bug Report: Node <=18 - `Unknown BridgeError: crypto is not defined`

### ISSUE THREAD

**Issue by rifont** [notifirehq/notifire#6982]
### 📜 Description

When using Node 18 that doesn't contain the global `crypto` WebCrypto API, Framework 2.4.0 fails to be invoked with `strictAuthentication: true` during the HMAC validation.

```bash
[Error]: Unknown BridgeError: crypto is not defined
    at bt.handleError (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:6281)
    at bt.handleAction (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:4889)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:3618 {
  data: {
    stack: 'ReferenceError: crypto is not defined\n' +
      '    at Or (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:1:11777)\n' +
      '    at bt.validateHmac (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:6587)\n' +
      '    at bt.handleAction (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:4619)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async /app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:3618'
  },
  statusCode: 500,
  code: 'BridgeError'
}
```

### 👟 Reproduction steps

1. Install `@novu/framework`@2.4.0, serve a workflow with a Node 18 or less runtime.
2. Attempt to sync the Workflow with `strictAuthentication: true`

### 👍 Expected behavior

Sync should be successfull

### 👎 Actual Behavior with Screenshots

Sync fails with error:

```bash
[Error]: Unknown BridgeError: crypto is not defined
    at bt.handleError (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:6281)
    at bt.handleAction (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:4889)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:3618 {
  data: {
    stack: 'ReferenceError: crypto is not defined\n' +
      '    at Or (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:1:11777)\n' +
      '    at bt.validateHmac (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:6587)\n' +
      '    at bt.handleAction (/app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:4619)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async /app/node_modules/@novu/framework/dist/cjs/servers/express.cjs:95:3618'
  },
  statusCode: 500,
  code: 'BridgeError'
}
```

### Novu version

Novu SaaS

### node version

18

### 📃 Provide any additional context for the Bug.

A polyfill for global `crypto` should be added in Node environments with version 18 or less.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by SokratisVidros** [comment]
Node 18 will reach its [end-of-life on the 2025-04-30](https://github.com/nodejs/Release?tab=readme-ov-file). Consider using a newer Node version.
